 #                                            Numpy
##### what's ?

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.

##### who can use?
    NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development
##### Application
    The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.
    NumPy can be used to perform a wide variety of mathematical operations on arrays.




#### Why use NumPy?

    NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

##### Numpy container
- The NumPy library contains multidimensional array and matrix data structures. 
- It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. 
- It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.




## What is Numpy array?
  1. An array is a central data structure of the NumPy library. 
  2. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. 
  3. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.
  4. An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. 

  5. One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.


- The array object represents a multidimensional, homogeneous array of fixed-size items.  
- An associated data-type object describes the format of each element in the array (its byte-order, how many bytes it occupies in memory, whether it is an integer, a floating point number, or something else, etc.)

    
        
Arrays should be constructed using `np.array()`,

To create a NumPy array, you can use the function `np.array()`.
- For example

In [19]:
import numpy as np
import math as calc

a = np.array([1, 2, 3, 4, 5, 6])# array with a single list

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])#numpy array with two list

print(a,b)


[1 2 3 4 5 6] [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### What’s the difference between a Python list and a NumPy array?
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

#### Parameters of NumpyArray
    ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)
1. shape : tuple of ints
    Shape of created array.
2. dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
3. buffer : object exposing buffer interface, optional
    Used to fill the array with data.
4. offset : int, optional
    Offset of array data in buffer.
5. strides : tuple of ints, optional
    Strides of data in memory.
6. order : {'C', 'F'}, optional
    Row-major (C-style) or column-major (Fortran-style) order.
    

For example

In [65]:
a = np.array([1, 2, 3, 4, 5, 6], dtype = int)# array with a single list and a type = int

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])#numpy array with two list
a

array([1, 2, 3, 4, 5, 6])

### Properties

- `ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

- `ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

- `ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).


For example:

In [70]:
b = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

dimen = b.ndim
print(dimen)

size = b.size
print(size)

shape = b.shape
print(shape)

2
12
(3, 4)


### Reshaping
- Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

For exmaple: We can reshape b from (3,4) to (4,3)

In [72]:
a = b.reshape(4,3)

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshaping with optional parameters

    numpy.reshape(a, newshape=(1, 6), order='C')
    
- a is the array to be reshaped.

- newshape is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

- order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)


In [76]:
import numpy as np
newArr = np.reshape(a, newshape=(6,2), order = 'C')
print(newArr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


## Other Different ways of creating numpy array list 

`np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`

### np.zeros()
Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s

In [23]:
b = np.zeros(2)
b

array([0., 0.])

### np.ones()
an array filled with 1’s:

In [25]:
c = np.ones(2)
c

array([1., 1.])

### np.empty()
Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!



In [35]:
 # Create an empty array with 2 elements
d = np.empty(2)
d

array([1., 1.])

### np.arange()
You can create an array with a range of elements: The code below creates a 1D array from 0-3

In [29]:
e = np.arange(4)
e

array([0, 1, 2, 3])

And even an array that contains a range of evenly spaced intervals. 

   To do this, you will specify the `first number`, `last number`, and the `step size`.

In [31]:
a = np.arange(2, 9, 2)
a

array([2, 4, 6, 8])

### np.linspace()
You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:



In [38]:
lin = np.linspace(0, 10, num=3)
lin

array([ 0.,  5., 10.])

## Adding, removing, and sorting elements

    This section covers np.sort(), np.concatenate()
    

### Sorting
Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

If you start with this array:


In [42]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

You can quickly sort the numbers in ascending order with:

In [44]:
ascending = np.sort(arr)
ascending

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to sort, which returns a sorted copy of an array, you can use:

- argsort, which is an indirect sort along a specified axis,

- lexsort, which is an indirect stable sort on multiple keys,

- searchsorted, which will find elements in a sorted array, and

- partition, which is a partial sort.

To learn more, see [https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort]

### Concatenation
You can concatenate them with np.concatenate((arrs), axis='x or y').
- The arrs are the arrays to be concatenated
- axis are the dimenstion for concatenated arrs: 

x = 0, for 1D array, y = 1 nD array

Note: if you choose your axis = 1,then your array rows of a = array colum of b

all the input array dimensions for the concatenation axis must match exactly

For example:

In [46]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [53]:
ab = np.concatenate((a,b), axis = 0)
ab

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

res = np.concatenate((x,y), axis = 0)# adding y to x, so, y will be next array list of x
res

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7,8]])

res = np.concatenate((x,y), axis = 0)# adding y to x, so, y will be next array list of x on 2 rows
res

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [77]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7,8]])

res = np.concatenate((x,y), axis = 1)# adding y to x, so, y will be next column array list of x
res

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### How to convert a 1D array into a 2D array (how to add a new axis to an array)
You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

Using `np.newaxis` will increase the dimensions of your array by one dimension when used once. 
This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

For example:


In [79]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

(6,)


You can use `np.newaxis` to add a new axis: either row or colum

In [86]:
#adding it to a row
a2 = a[np.newaxis,:]
print(a2.shape)
a2

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [87]:
#adding it to column
a2 = a[:, np.newaxis]
print(a2.shape)
a2

(6, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

For example, if you start with this array:




In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [90]:
#You can use np.expand_dims to add an axis at index position 1 with:
b = np.expand_dims(a, axis=1)
print(b.shape)

# You can use np.expand_dims to add an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
print(c.shape)

(6, 1)
(1, 6)
